extern void meminfo();
extern unsigned kb_main_total;
extern unsigned kb_main_free;
extern unsigned kb_main_used;
extern unsigned kb_main_buffers;
extern unsigned kb_main_cached;
extern unsigned kb_swap_total;
extern unsigned kb_swap_free;
extern unsigned kb_swap_used;
